# Generated by Django 6.0.6 on 2026-07-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_alter_perfilusuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
