# Generated by Django 5.2.9 on 2026-06-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nt', models.CharField(max_length=20, unique=True)),
                ('etiqueta', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('000-Generalidades', '000-Generalidades'), ('300-Ciencias Sociales', '300-Ciencias Sociales'), ('400-Lenguas', '400-Lenguas'), ('500-Ciencias naturales y matemáticas', '500-Ciencias naturales y matemáticas'), ('600-Tecnología (Ciencia aplicadas)', '600-Tecnología (Ciencia aplicadas)'), ('700-Bellas artes', '700-Bellas artes'), ('800-Literatura y retórica', '800-Literatura y retórica'), ('900-Geografía e Historia', '900-Geografía e Historia'), ('Préstamo a domicilio', 'Préstamo a domicilio')], default='000-Generalidades', max_length=50)),
                ('ejemplares', models.IntegerField(default=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='libros/')),
                ('estado', models.CharField(choices=[('enInventario', 'En Inventario'), ('prestado', 'Prestado'), ('sinExistencias', 'Sin Existencias')], default='enInventario', max_length=20)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registrado_en'],
            },
        ),
    ]
