# Generated by Django 6.0.6 on 2026-07-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_libro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
